import SunflowerAASC

namespace SunflowerAASC

/-! The focused public axiom audit for the manuscript-matched closure spine. -/

#print axioms sunflowerAPlusObligationCount_eq
#print axioms SunflowerAPlusAuditCertificate.auditSurfaceComplete_holds
#print axioms SunflowerAPlusAuditCertificate.transfer_to_BMF

#print axioms V2.Concrete.FiniteCoreLinkMatching.rawBlocker_card_le_pred_mul_rank
#print axioms V2.SelectedCoordinateReduction.family_card_le_k_mul_residualFamily
#print axioms V2.SelectedCoordinateReduction.residualLiftInterference_of_noSunflower
#print axioms V2.SelectedCoordinateReduction.residualLiftCrossProfile_nonempty_of_noSunflower
#print axioms V2.SelectedCoordinateReduction.residualLiftCrossProfile_card_le
#print axioms V2.SelectedCoordinateReduction.hasSunflower_or_outgoingCross_of_residualFamily
#print axioms V2.SelectedCoordinateReduction.residualFamily_noSunflower_of_noOutgoingCross
#print axioms V2.GeneratedIncidenceTower.nextCoordinate_nonempty
#print axioms V2.GeneratedIncidenceTower.incidencePath_nonempty
#print axioms V2.GeneratedIncidenceTower.exists_reachesTerminalCarrier
#print axioms V2.GeneratedIncidenceTower.terminalFamily_noSunflower
#print axioms V2.GeneratedSeedCapacity.KernelFaithfulEndpointRoleBridge.cellCarrierOf_injective
#print axioms V2.GeneratedSeedCapacity.nonempty_endpointRoleBridge_iff_cellCarrierOf_injective
#print axioms V2.GeneratedSeedCapacity.KernelFaithfulEndpointRoleBridge.cell_card_le_4094
#print axioms V2.GeneratedSeedCapacity.KernelFaithfulStandingPathBridge.standingCarrier_reachable
#print axioms V2.GeneratedSeedCapacity.KernelFaithfulStandingPathBridge.standingCarrier_choice_independent
#print axioms V2.GeneratedSeedCapacity.KernelFaithfulStandingPathBridge.standingCarrierOf_injective
#print axioms V2.GeneratedSeedCapacity.KernelFaithfulStandingPathBridge.cell_card_le_4094
#print axioms V2.PopulationInheritance.threePetalTraditionalSeedTensorProfileBound_eq
#print axioms V2.PopulationInheritance.threePetalTraditionalSeedConstraintBase_eq
#print axioms V2.PopulationInheritance.no_threePetal_denseCountercase_through_seedReflectedCutoff

#print axioms V2.FixedIdentityPopulation.nonempty_sameSideExhaustion_iff_fixedIdentityRealization
#print axioms V2.FixedIdentityPopulation.KernelFaithfulFixedIdentityRealization.identity_preserved_at_rank
#print axioms V2.HighRankPopulationInheritance.population_or_oversizedCanonicalSupportFiber
#print axioms V2.HighRankPopulationInheritance.nonempty_boundedLoadExhaustion_iff_canonicalSupportFiberBound

#print axioms V2.ManuscriptKernelTransfer.neutralEndpointAdequacy_iff_targetAdequate
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperNothingDerivableBelowKernelStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperGlobalSynthesisUnderCorpusClosuresClosedStatement
#print axioms V2.MechanizedKernelImport.mechanizedKernelDependencyCertificate
#print axioms V2.ManuscriptKernelTransfer.KernelImportRoute.noSameDomainDerivationBelowKernel
#print axioms V2.ManuscriptKernelTransfer.KernelImportRoute.governanceEquivalentReplacement_hasKernel
#print axioms V2.ManuscriptKernelTransfer.KernelImportRoute.activation
#print axioms V2.ManuscriptKernelTransfer.KernelImportRoute.denialAndStrictWeakeningExhausted
#print axioms V2.ManuscriptKernelTransfer.ThreePetalLocalManuscriptPopulation.fixedIdentityPopulation
#print axioms V2.ManuscriptKernelTransfer.ThreePetalLocalManuscriptPopulation.canonicalSupportFiberBound
#print axioms V2.ManuscriptKernelTransfer.ImportedManuscriptKernelGovernedPopulationTheorem.toKernelGovernedFiberClosureSource
#print axioms V2.ManuscriptKernelTransfer.sunflower_of_importedManuscriptKernelGovernedClosure
#print axioms V2.ManuscriptKernelTransfer.ImportedManuscriptKernelGovernedPopulationTheorem.provesEndpointBound
#print axioms V2.ManuscriptKernelTransfer.nonempty_importedManuscriptPopulationTheorem_iff_endpointBound

end SunflowerAASC
