import Mathlib.Data.Prod.Lex
import SunflowerAASC.V2.RootAuthenticScopeCorrespondence

namespace SunflowerAASC
namespace V2
namespace ExplicitReductionPotential

/--
The finite data carried by one active countercase package. The certificate
ledger records only literal certificates already present in the package.
-/
structure CountercasePackage
    (Vertex ScopeData GeneratedCtor Certificate : Type)
    [DecidableEq Vertex]
    [DecidableEq GeneratedCtor]
    [DecidableEq Certificate] where
  rank : Nat
  family : Finset (Finset Vertex)
  family_uniform : forall edge, edge ∈ family -> edge.card = rank
  scopeData : ScopeData
  constructorDomain : Finset GeneratedCtor
  certificateLedger : Finset Certificate

/-- The literal active support generated by the finite family. -/
def activeSupport
    {Vertex ScopeData GeneratedCtor Certificate : Type}
    [DecidableEq Vertex]
    [DecidableEq GeneratedCtor]
    [DecidableEq Certificate]
    (P : CountercasePackage Vertex ScopeData GeneratedCtor Certificate) :
    Finset Vertex :=
  P.family.biUnion (fun edge : Finset Vertex => edge)

/-- The manuscript's four-coordinate reduction potential. -/
structure ReductionPotential where
  rank : Nat
  familyCard : Nat
  supportCard : Nat
  ctorCard : Nat
deriving DecidableEq, Repr

/-- Right-associated tuple used by the ordinary product lexicographic order. -/
def ReductionPotential.toLexTuple (potential : ReductionPotential) :
    Nat × (Nat × (Nat × Nat)) :=
  (potential.rank,
    (potential.familyCard, (potential.supportCard, potential.ctorCard)))

/-- Strict lexicographic comparison: rank, family, support, constructors. -/
def ReductionPotential.LexLt
    (left right : ReductionPotential) : Prop :=
  Prod.Lex (· < ·)
    (Prod.Lex (· < ·) (Prod.Lex (· < ·) (· < ·)))
    left.toLexTuple right.toLexTuple

/-- The concrete potential of a finite package. -/
def potential
    {Vertex ScopeData GeneratedCtor Certificate : Type}
    [DecidableEq Vertex]
    [DecidableEq GeneratedCtor]
    [DecidableEq Certificate]
    (P : CountercasePackage Vertex ScopeData GeneratedCtor Certificate) :
    ReductionPotential where
  rank := P.rank
  familyCard := P.family.card
  supportCard := (activeSupport P).card
  ctorCard := P.constructorDomain.card

/-- The four-coordinate lexicographic potential is well founded. -/
theorem reductionPotential_wellFounded :
    WellFounded ReductionPotential.LexLt := by
  exact InvImage.wf ReductionPotential.toLexTuple
    (wellFounded_lt.prod_lex
      (wellFounded_lt.prod_lex
        (wellFounded_lt.prod_lex wellFounded_lt)))

/-- Certified reduction induced by an explicit potential map. -/
def PackageLt {Pkg : Type}
    (measure : Pkg -> ReductionPotential)
    (left right : Pkg) : Prop :=
  ReductionPotential.LexLt (measure left) (measure right)

/-- Every package reduction induced by the potential is well founded. -/
theorem packageLt_wellFounded {Pkg : Type}
    (measure : Pkg -> ReductionPotential) :
    WellFounded (PackageLt measure) := by
  exact InvImage.wf measure reductionPotential_wellFounded

/-- The concrete countercase-package reduction is well founded. -/
theorem countercasePackageLt_wellFounded
    {Vertex ScopeData GeneratedCtor Certificate : Type}
    [DecidableEq Vertex]
    [DecidableEq GeneratedCtor]
    [DecidableEq Certificate] :
    WellFounded (PackageLt
      (@potential Vertex ScopeData GeneratedCtor Certificate _ _ _)) :=
  packageLt_wellFounded
    (@potential Vertex ScopeData GeneratedCtor Certificate _ _ _)

section CertifiedReduction

variable {Pkg : Type}
variable (measure : Pkg -> ReductionPotential)
variable (Endpoint : Pkg -> Prop)

/--
A direct closeout is literal evidence that settles the current package. A
reconstruction closeout records its complete nonempty factor list, decrease
witnesses, already proved factor endpoints, and reconstruction map.
-/
inductive DirectCloseoutCertificate (P : Pkg) : Type
  | reflectedRange (endpoint : Endpoint P)
  | lowerRank (endpoint : Endpoint P)
  | reconstruction
      (factors : List Pkg)
      (nonempty : factors ≠ [])
      (decreases : forall Q, Q ∈ factors -> PackageLt measure Q P)
      (factorEndpoints : forall Q, Q ∈ factors -> Endpoint Q)
      (reconstruct :
        (forall Q, Q ∈ factors -> Endpoint Q) -> Endpoint P)

/-- Every literal direct closeout proves the endpoint it advertises. -/
def DirectCloseoutCertificate.settles
    {measure : Pkg -> ReductionPotential}
    {Endpoint : Pkg -> Prop}
    {P : Pkg}
    (certificate : DirectCloseoutCertificate measure Endpoint P) :
    Endpoint P := by
  cases certificate with
  | reflectedRange endpoint => exact endpoint
  | lowerRank endpoint => exact endpoint
  | reconstruction _ _ _ factorEndpoints reconstruct =>
      exact reconstruct factorEndpoints

variable (PreservesTargetScope : Pkg -> List Pkg -> Prop)

/--
An endpoint-faithful split has a fixed nonempty finite factor list, a strict
potential decrease on every factor, a reconstruction map, and a target/scope
preservation witness.
-/
structure EndpointFaithfulSplit (P : Pkg) where
  factors : List Pkg
  nonempty : factors ≠ []
  decreases : forall Q, Q ∈ factors -> PackageLt measure Q P
  reconstruct :
    (forall Q, Q ∈ factors -> Endpoint Q) -> Endpoint P
  endpointFaithful : PreservesTargetScope P factors

variable (SunflowerCertificate : Pkg -> Prop)

/-- No literal sunflower, direct closeout, or certified split remains. -/
def TerminalPackage (P : Pkg) : Prop :=
  Not (SunflowerCertificate P) ∧
    Not (Nonempty (DirectCloseoutCertificate measure Endpoint P)) ∧
    Not (Nonempty
      (EndpointFaithfulSplit measure Endpoint PreservesTargetScope P))

/-- The complete literal disposition used by certified terminalization. -/
def CertifiedDisposition (P : Pkg) : Prop :=
  SunflowerCertificate P ∨
    Nonempty (DirectCloseoutCertificate measure Endpoint P) ∨
    Nonempty
      (EndpointFaithfulSplit measure Endpoint PreservesTargetScope P) ∨
    TerminalPackage measure Endpoint PreservesTargetScope
      SunflowerCertificate P

/--
A finite certified derivation tree. Split nodes contain precisely the fixed
finite factor list carried by their certificate and one child derivation for
each listed factor.
-/
inductive CertifiedDerivation : Pkg -> Type
  | settled {P : Pkg} (endpoint : Endpoint P) : CertifiedDerivation P
  | terminal {P : Pkg}
      (certificateTerminal :
        TerminalPackage measure Endpoint PreservesTargetScope
          SunflowerCertificate P) :
      CertifiedDerivation P
  | split {P : Pkg}
      (certificate :
        EndpointFaithfulSplit measure Endpoint PreservesTargetScope P)
      (children : forall Q, Q ∈ certificate.factors -> CertifiedDerivation Q) :
      CertifiedDerivation P

/-- Every certified split has a finite, nonempty, fixed branch list. -/
theorem certifiedSplit_finiteBranching
    {P : Pkg}
    (certificate :
      EndpointFaithfulSplit measure Endpoint PreservesTargetScope P) :
    certificate.factors ≠ [] :=
  certificate.nonempty

/--
Well-founded recursion resolves every package into a finite derivation tree.
Every leaf is settled or terminal and every split edge carries the literal
strict decrease witness from its certificate.
-/
theorem certified_terminalization
    (sunflowerSettles :
      forall P : Pkg, SunflowerCertificate P -> Endpoint P)
    (disposition :
      forall P : Pkg,
        CertifiedDisposition measure Endpoint PreservesTargetScope
          SunflowerCertificate P)
    (P : Pkg) :
    Nonempty (CertifiedDerivation measure Endpoint PreservesTargetScope
      SunflowerCertificate P) := by
  induction P using (packageLt_wellFounded measure).induction with
  | h P smaller =>
      rcases disposition P with
        sunflower | closeout | split | terminal
      · exact ⟨CertifiedDerivation.settled
          (sunflowerSettles P sunflower)⟩
      · exact ⟨CertifiedDerivation.settled
          closeout.some.settles⟩
      · let children : forall Q, Q ∈ split.some.factors ->
            CertifiedDerivation measure Endpoint PreservesTargetScope
              SunflowerCertificate Q :=
          fun Q member => Classical.choice
            (smaller Q (split.some.decreases Q member))
        exact ⟨CertifiedDerivation.split split.some children⟩
      · exact ⟨CertifiedDerivation.terminal terminal⟩

/--
Read a certified derivation after the terminal AASC layer has been closed.
Raw sources need not inject into terminal coordinates: split nodes reconstruct
from smaller packages, and only the quotient-stable terminal leaves cross the
closeout theorem.
-/
theorem CertifiedDerivation.settles_of_terminalCloseout
    (terminalCloseout :
      forall P : Pkg,
        TerminalPackage measure Endpoint PreservesTargetScope
          SunflowerCertificate P -> Endpoint P)
    {P : Pkg}
    (derivation : CertifiedDerivation measure Endpoint PreservesTargetScope
      SunflowerCertificate P) :
    Endpoint P := by
  induction derivation with
  | settled endpoint => exact endpoint
  | terminal certificateTerminal =>
      exact terminalCloseout _ certificateTerminal
  | split certificate children childrenSettle =>
      exact certificate.reconstruct childrenSettle

/--
Finite disposition exhaustion plus post-exhaustion terminal closeout proves
the endpoint. This is the generic AASC proof mode: generation supplies the
disposition tree, while exhaustion and impossibility settle its terminal
leaves.
-/
theorem endpoint_of_exhaustion_and_terminalCloseout
    (sunflowerSettles :
      forall P : Pkg, SunflowerCertificate P -> Endpoint P)
    (disposition :
      forall P : Pkg,
        CertifiedDisposition measure Endpoint PreservesTargetScope
          SunflowerCertificate P)
    (terminalCloseout :
      forall P : Pkg,
        TerminalPackage measure Endpoint PreservesTargetScope
          SunflowerCertificate P -> Endpoint P)
    (P : Pkg) :
    Endpoint P := by
  let derivation : CertifiedDerivation measure Endpoint PreservesTargetScope
      SunflowerCertificate P :=
    Classical.choice
      (certified_terminalization measure Endpoint PreservesTargetScope
        SunflowerCertificate sunflowerSettles disposition P)
  exact CertifiedDerivation.settles_of_terminalCloseout
    (measure := measure) (Endpoint := Endpoint)
    (PreservesTargetScope := PreservesTargetScope)
    (SunflowerCertificate := SunflowerCertificate)
    terminalCloseout derivation

/-- A terminal impossibility theorem is a special case of terminal closeout. -/
theorem endpoint_of_exhaustion_and_terminalImpossibility
    (sunflowerSettles :
      forall P : Pkg, SunflowerCertificate P -> Endpoint P)
    (disposition :
      forall P : Pkg,
        CertifiedDisposition measure Endpoint PreservesTargetScope
          SunflowerCertificate P)
    (terminalImpossible :
      forall P : Pkg,
        TerminalPackage measure Endpoint PreservesTargetScope
          SunflowerCertificate P -> False)
    (P : Pkg) :
    Endpoint P :=
  endpoint_of_exhaustion_and_terminalCloseout
    measure Endpoint PreservesTargetScope SunflowerCertificate
    sunflowerSettles disposition
    (fun Q terminal => False.elim (terminalImpossible Q terminal)) P

/-- A countercase is simply failure of the fixed endpoint proposition. -/
def Countercase (P : Pkg) : Prop :=
  Not (Endpoint P)

/-- No strictly smaller package is a countercase to the same endpoint. -/
def ReductionMinimalCountercase (P : Pkg) : Prop :=
  Countercase Endpoint P ∧
    forall Q, PackageLt measure Q P -> Not (Countercase Endpoint Q)

/-- A minimal countercase cannot carry a literal direct closeout. -/
theorem reductionMinimalCountercase_no_closeout
    {P : Pkg}
    (minimal : ReductionMinimalCountercase measure Endpoint P) :
    Not (Nonempty (DirectCloseoutCertificate measure Endpoint P)) := by
  intro closeout
  exact minimal.1 closeout.some.settles

/-- A minimal countercase cannot carry a settling sunflower certificate. -/
theorem reductionMinimalCountercase_no_sunflower
    (sunflowerSettles :
      forall P : Pkg, SunflowerCertificate P -> Endpoint P)
    {P : Pkg}
    (minimal : ReductionMinimalCountercase measure Endpoint P) :
    Not (SunflowerCertificate P) := by
  intro sunflower
  exact minimal.1 (sunflowerSettles P sunflower)

/-- A minimal countercase cannot carry an endpoint-faithful split. -/
theorem reductionMinimalCountercase_no_split
    {P : Pkg}
    (minimal : ReductionMinimalCountercase measure Endpoint P) :
    Not (Nonempty
      (EndpointFaithfulSplit measure Endpoint PreservesTargetScope P)) := by
  intro split
  apply minimal.1
  apply split.some.reconstruct
  intro Q member
  apply Classical.byContradiction
  exact minimal.2 Q (split.some.decreases Q member)

/-- Every reduction-minimal countercase is certificate-terminal. -/
theorem reductionMinimal_countercase_terminal
    (sunflowerSettles :
      forall P : Pkg, SunflowerCertificate P -> Endpoint P)
    {P : Pkg}
    (minimal : ReductionMinimalCountercase measure Endpoint P) :
    TerminalPackage measure Endpoint PreservesTargetScope
      SunflowerCertificate P := by
  exact
    ⟨reductionMinimalCountercase_no_sunflower measure Endpoint
        SunflowerCertificate sunflowerSettles minimal,
      reductionMinimalCountercase_no_closeout measure Endpoint minimal,
      reductionMinimalCountercase_no_split measure Endpoint
        PreservesTargetScope minimal⟩

end CertifiedReduction

end ExplicitReductionPotential
end V2
end SunflowerAASC
