import SunflowerAASC.V2.CompleteRoleRefinement
import SunflowerAASC.V2.HighRankPopulationInheritance
import SunflowerAASC.V2.InternalTensorProfiles

namespace SunflowerAASC
namespace V2
namespace ResidualParentExhaustion

open CompleteRoleRefinement
open InternalTensorProfiles

/-- The two finite AASC classifiers used by the residual-parent route map. -/
structure ResidualParentClassifiers
    {alpha : Type}
    [DecidableEq alpha]
    {r : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1)) where
  constraintProfile :
    {x // x ∈ MinimalBlocker.minimalBlocker F} ->
      Finset ConstraintMapPopulation.ConstraintMapLevel
  forcedRole :
    {x // x ∈ MinimalBlocker.minimalBlocker F} -> AASCBlockerRole

/--
The target-specific impossibility statement left after local finite
combinatorics.  Two private witnesses that agree on the inherited support,
constraint profile, and forced AASC role cannot retain distinct residual
parents inside one fixed endpoint.

This predicate contains no finite code, cardinal bound, Hall statement, or
endpoint theorem.
-/
def FixedCellResidualParentTensorImpossibility
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower k F))
    (classifiers : ResidualParentClassifiers F) : Prop :=
  forall left right : {x // x ∈ MinimalBlocker.minimalBlocker F},
    BlockerSupportLayers.canonicalSupportLayerCell F noSunflower
        ⟨left.val, MinimalBlocker.minimalBlocker_subset_raw F left.property⟩ =
      BlockerSupportLayers.canonicalSupportLayerCell F noSunflower
        ⟨right.val, MinimalBlocker.minimalBlocker_subset_raw F right.property⟩ ->
    classifiers.constraintProfile left = classifiers.constraintProfile right ->
    classifiers.forcedRole left = classifiers.forcedRole right ->
    ResidualParentTensorDistinction F left right ->
    False

/--
The finite route map for a realized private-witness load.  Skin is already
excluded by the private edge.  The load therefore either changes the bounded
`Fin k` slot inside one residual parent, or changes the residual parent itself.
-/
theorem privateWitnessLoad_exhausts_into_boundedSlot_or_residualParent
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower k F))
    (left right : {x // x ∈ MinimalBlocker.minimalBlocker F})
    (load : MinimalBlocker.PrivateWitnessEndpointLoad F left right) :
    Or (BoundedFiberSlotDistinction F noSunflower left right)
      (ResidualParentTensorDistinction F left right) := by
  have distinct : Not (left = right) := by
    intro same
    subst right
    exact load.rightNegative load.leftPositive
  rcases distinct_exhausts_into_parentTensor_or_boundedFiberSlot
      F noSunflower left right distinct with tensor | bounded
  · exact Or.inr tensor
  · exact Or.inl bounded

/--
The concrete prime-changing branch used by the generic four-route closeout.
It records all three fixed-cell equalities together with a genuine change of
residual parent.
-/
def FixedCellResidualParentTensorSplit
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower k F))
    (classifiers : ResidualParentClassifiers F)
    (left right : {x // x ∈ MinimalBlocker.minimalBlocker F}) : Prop :=
  BlockerSupportLayers.canonicalSupportLayerCell F noSunflower
      ⟨left.val, MinimalBlocker.minimalBlocker_subset_raw F left.property⟩ =
    BlockerSupportLayers.canonicalSupportLayerCell F noSunflower
      ⟨right.val, MinimalBlocker.minimalBlocker_subset_raw F right.property⟩ /\
  classifiers.constraintProfile left = classifiers.constraintProfile right /\
  classifiers.forcedRole left = classifiers.forcedRole right /\
  ResidualParentTensorDistinction F left right

/-- The fixed-cell impossibility eliminates exactly the tensor-split branch. -/
theorem fixedCellResidualParentTensorSplit_impossible
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    {F : Concrete.UniformSetFamily alpha (r + 1)}
    {noSunflower : Not (Concrete.HasSunflower k F)}
    {classifiers : ResidualParentClassifiers F}
    (impossible : FixedCellResidualParentTensorImpossibility
      F noSunflower classifiers)
    (left right : {x // x ∈ MinimalBlocker.minimalBlocker F})
    (split : FixedCellResidualParentTensorSplit
      F noSunflower classifiers left right) :
    False := by
  exact impossible left right split.1 split.2.1 split.2.2.1 split.2.2.2

/--
Exhaustion plus impossibility constructs the bounded population object.  The
bounded profile is not assumed: it is the concrete residual-fibre slot already
generated by finite combinatorics.
-/
noncomputable def boundedLoadExhaustionOfResidualParentImpossibility
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    {F : Concrete.UniformSetFamily alpha (r + 1)}
    {noSunflower : Not (Concrete.HasSunflower k F)}
    {corpus : KernelFirstCorpusMachinery
      (Concrete.concreteSunflowerCarrier alpha (r + 1) k)}
    (k_positive : 0 < k)
    (classifiers : ResidualParentClassifiers F)
    (impossible : FixedCellResidualParentTensorImpossibility
      F noSunflower classifiers) :
    BoundedPrivateWitnessLoadExhaustion
      (tensorProfileBound := k) noSunflower corpus where
  tensorProfileBound_positive := k_positive
  constraintProfile := classifiers.constraintProfile
  forcedRole := classifiers.forcedRole
  internalTensorProfileSlot :=
    PrivateWitnessReduction.residualFiberSlot F noSunflower
  primeChangingTensorSplit :=
    FixedCellResidualParentTensorSplit F noSunflower classifiers
  loadExhaustive := by
    intro left right sameCell sameProfile sameRole load
    rcases privateWitnessLoad_exhausts_into_boundedSlot_or_residualParent
        F noSunflower left right load with bounded | tensor
    · exact Or.inl bounded.2
    · exact Or.inr <| Or.inl
        ⟨sameCell, sameProfile, sameRole, tensor⟩
  primeChangingTensorSplitExcluded := by
    intro left right split
    exact fixedCellResidualParentTensorSplit_impossible
      impossible left right split

/-- The resulting complete finite identity code is injective. -/
theorem residualParentExhaustion_code_injective
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    {F : Concrete.UniformSetFamily alpha (r + 1)}
    {noSunflower : Not (Concrete.HasSunflower k F)}
    {corpus : KernelFirstCorpusMachinery
      (Concrete.concreteSunflowerCarrier alpha (r + 1) k)}
    (k_positive : 0 < k)
    (classifiers : ResidualParentClassifiers F)
    (impossible : FixedCellResidualParentTensorImpossibility
      F noSunflower classifiers) :
    Function.Injective
      (boundedLoadExhaustionOfResidualParentImpossibility
        (corpus := corpus) k_positive classifiers impossible).code := by
  exact
    (boundedLoadExhaustionOfResidualParentImpossibility
      (corpus := corpus) k_positive classifiers impossible).code_injective

/--
A corpus-facing route into the impossibility statement.  It says only that a
surviving fixed-cell residual-parent split would have to act as an independent
same-domain authorizer.  The fixed-domain AASC theorem then rules it out.
-/
structure ResidualParentTensorAuthorizerRoute
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower k F))
    (corpus : KernelFirstCorpusMachinery
      (Concrete.concreteSunflowerCarrier alpha (r + 1) k))
    (classifiers : ResidualParentClassifiers F) where
  splitCreatesIndependentAuthorizer :
    forall left right : {x // x ∈ MinimalBlocker.minimalBlocker F},
      FixedCellResidualParentTensorSplit
          F noSunflower classifiers left right ->
      Exists (fun factor :
        (Concrete.concreteSunflowerCarrier alpha (r + 1) k).StandingFactor =>
        corpus.fixedDomainClosure.disposition factor =
          SameScopeFactorDisposition.independentAuthorizer)

/-- Fixed-domain AASC impossibility discharges the routed tensor branch. -/
theorem residualParentTensorImpossibility_of_authorizerRoute
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    {F : Concrete.UniformSetFamily alpha (r + 1)}
    {noSunflower : Not (Concrete.HasSunflower k F)}
    {corpus : KernelFirstCorpusMachinery
      (Concrete.concreteSunflowerCarrier alpha (r + 1) k)}
    {classifiers : ResidualParentClassifiers F}
    (route : ResidualParentTensorAuthorizerRoute
      F noSunflower corpus classifiers) :
    FixedCellResidualParentTensorImpossibility
      F noSunflower classifiers := by
  intro left right sameCell sameProfile sameRole tensor
  rcases route.splitCreatesIndependentAuthorizer left right
      ⟨sameCell, sameProfile, sameRole, tensor⟩ with ⟨factor, authorizer⟩
  exact corpus.fixedDomainClosure.excludesIndependentAuthorizer
    factor authorizer

/--
The complete one-rank pincer: finite combinatorics supplies the bounded slot,
and AASC impossibility removes only the residual-parent authorizer route.
-/
noncomputable def boundedLoadExhaustionOfAuthorizerRoute
    {alpha : Type}
    [DecidableEq alpha]
    {r k : Nat}
    {F : Concrete.UniformSetFamily alpha (r + 1)}
    {noSunflower : Not (Concrete.HasSunflower k F)}
    {corpus : KernelFirstCorpusMachinery
      (Concrete.concreteSunflowerCarrier alpha (r + 1) k)}
    (k_positive : 0 < k)
    (classifiers : ResidualParentClassifiers F)
    (route : ResidualParentTensorAuthorizerRoute
      F noSunflower corpus classifiers) :
    BoundedPrivateWitnessLoadExhaustion
      (tensorProfileBound := k) noSunflower corpus :=
  boundedLoadExhaustionOfResidualParentImpossibility
    k_positive classifiers
    (residualParentTensorImpossibility_of_authorizerRoute route)

/-- The private-residual tower specialized to the literal rank-one endpoint. -/
noncomputable def rankOneTerminalFamily
    {alpha : Type}
    [DecidableEq alpha] :
    (r : Nat) ->
      Concrete.UniformSetFamily alpha (r + 1) ->
      Concrete.UniformSetFamily alpha 1
  | 0, F => F
  | r + 1, F =>
      rankOneTerminalFamily r (PrivateWitnessReduction.residualFamily F)

/--
A generated rank-one carrier. Every recursive step chooses from the already
proved nonempty blocker-incidence continuation; no injectivity is used.
-/
noncomputable def rankOneGeneratedCarrier
    {alpha : Type}
    [DecidableEq alpha] :
    (r : Nat) ->
    (F : Concrete.UniformSetFamily alpha (r + 1)) ->
    {x // x ∈ MinimalBlocker.minimalBlocker F} ->
    {x // x ∈ MinimalBlocker.minimalBlocker (rankOneTerminalFamily r F)}
  | 0, _F, source => source
  | r + 1, F, source =>
      let target := Classical.choice
        (GeneratedIncidenceTower.nextCoordinate_nonempty F source)
      rankOneGeneratedCarrier r
        (PrivateWitnessReduction.residualFamily F) target.val

/-- Private residualization preserves the three-petal countercase to rank one. -/
theorem rankOneTerminalFamily_noSunflower
    {alpha : Type}
    [DecidableEq alpha]
    (r : Nat)
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower 3 F)) :
    Not (Concrete.HasSunflower 3 (rankOneTerminalFamily r F)) := by
  induction r with
  | zero =>
      exact noSunflower
  | succ r ih =>
      exact ih (PrivateWitnessReduction.residualFamily F)
        (PrivateWitnessReduction.residualFamily_noSunflower noSunflower)

/--
Every positive-rank three-petal source has a generated terminal seed at rank
one.  The codomain has two slots by the traditional rank-one blocker bound.
-/
noncomputable def rankOneTerminalSeedSlot
    {alpha : Type}
    [DecidableEq alpha]
    {r : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower 3 F)) :
    {x // x ∈ MinimalBlocker.minimalBlocker F} ->
      Fin (PopulationInheritance.traditionalSeedTensorProfileBound 3 1) :=
  fun source =>
    PopulationInheritance.traditionalSeedProfileEmbedding
      (r := 0)
      (k := 3)
      (cutoff := 1)
      (by decide)
      (rankOneTerminalFamily r F)
      (rankOneTerminalFamily_noSunflower r F noSunflower)
      (rankOneGeneratedCarrier r F source)

/--
The rank-one terminal seed and the local `Fin 3` residual-fibre slot occupy
only six of the manuscript's 4094 inherited tensor-profile positions.
-/
noncomputable def rankOneSeedResidualSlotEmbedding :
    (Fin (PopulationInheritance.traditionalSeedTensorProfileBound 3 1) ×
      Fin 3) ↪
    Fin (PopulationInheritance.traditionalSeedTensorProfileBound 3
      PopulationInheritance.threePetalTraditionalCutoff) := by
  let sourceEquiv :
      (Fin (PopulationInheritance.traditionalSeedTensorProfileBound 3 1) ×
        Fin 3) ≃ Fin 6 :=
    Fintype.equivFinOfCardEq (by decide)
  let inclusion : Fin 6 ↪
      Fin (PopulationInheritance.traditionalSeedTensorProfileBound 3
        PopulationInheritance.threePetalTraditionalCutoff) :=
    ⟨Fin.castLE (by decide), by
      intro left right same
      apply Fin.ext
      simpa using congrArg Fin.val same⟩
  exact sourceEquiv.toEmbedding.trans inclusion

/-- The fully generated finite profile used before AASC collision governance. -/
noncomputable def generatedResidualProfileSlot
    {alpha : Type}
    [DecidableEq alpha]
    {r : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower 3 F)) :
    {x // x ∈ MinimalBlocker.minimalBlocker F} ->
      Fin (PopulationInheritance.traditionalSeedTensorProfileBound 3
        PopulationInheritance.threePetalTraditionalCutoff) :=
  fun source => rankOneSeedResidualSlotEmbedding
    (rankOneTerminalSeedSlot F noSunflower source,
      PrivateWitnessReduction.residualFiberSlot F noSunflower source)

theorem residualFiberSlot_eq_of_generatedResidualProfileSlot_eq
    {alpha : Type}
    [DecidableEq alpha]
    {r : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower 3 F))
    (left right : {x // x ∈ MinimalBlocker.minimalBlocker F})
    (sameSlot : generatedResidualProfileSlot F noSunflower left =
      generatedResidualProfileSlot F noSunflower right) :
    PrivateWitnessReduction.residualFiberSlot F noSunflower left =
      PrivateWitnessReduction.residualFiberSlot F noSunflower right := by
  have samePair := rankOneSeedResidualSlotEmbedding.injective sameSlot
  exact congrArg Prod.snd samePair

theorem rankOneTerminalSeedSlot_eq_of_generatedResidualProfileSlot_eq
    {alpha : Type}
    [DecidableEq alpha]
    {r : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower 3 F))
    (left right : {x // x ∈ MinimalBlocker.minimalBlocker F})
    (sameSlot : generatedResidualProfileSlot F noSunflower left =
      generatedResidualProfileSlot F noSunflower right) :
    rankOneTerminalSeedSlot F noSunflower left =
      rankOneTerminalSeedSlot F noSunflower right := by
  have samePair := rankOneSeedResidualSlotEmbedding.injective sameSlot
  exact congrArg Prod.fst samePair

/--
After both generated finite coordinates agree, the only surviving load branch
is a distinct residual-parent tensor profile in the same coarse comparison
cell.
-/
def GeneratedResidualParentTensorCollision
    {alpha : Type}
    [DecidableEq alpha]
    {r : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower 3 F))
    (classifiers : ResidualParentClassifiers F)
    (left right : {x // x ∈ MinimalBlocker.minimalBlocker F}) : Prop :=
  BlockerSupportLayers.canonicalSupportLayerCell F noSunflower
      ⟨left.val, MinimalBlocker.minimalBlocker_subset_raw F left.property⟩ =
    BlockerSupportLayers.canonicalSupportLayerCell F noSunflower
      ⟨right.val, MinimalBlocker.minimalBlocker_subset_raw F right.property⟩ /\
  classifiers.constraintProfile left = classifiers.constraintProfile right /\
  classifiers.forcedRole left = classifiers.forcedRole right /\
  generatedResidualProfileSlot F noSunflower left =
    generatedResidualProfileSlot F noSunflower right /\
  ResidualParentTensorDistinction F left right

/--
The sole AASC handoff left by the generated code: a residual-parent collision
with every finite coordinate fixed must route to the forbidden independent
authorizer disposition.
-/
structure ThreePetalGeneratedTensorAuthorizerRoute
    {alpha : Type}
    [DecidableEq alpha]
    {r : Nat}
    (F : Concrete.UniformSetFamily alpha (r + 1))
    (noSunflower : Not (Concrete.HasSunflower 3 F))
    (corpus : KernelFirstCorpusMachinery
      (Concrete.concreteSunflowerCarrier alpha (r + 1) 3))
    (classifiers : ResidualParentClassifiers F) where
  collisionCreatesIndependentAuthorizer :
    forall left right : {x // x ∈ MinimalBlocker.minimalBlocker F},
      GeneratedResidualParentTensorCollision
          F noSunflower classifiers left right ->
      Exists (fun factor :
        (Concrete.concreteSunflowerCarrier alpha (r + 1) 3).StandingFactor =>
        corpus.fixedDomainClosure.disposition factor =
          SameScopeFactorDisposition.independentAuthorizer)

/--
Concrete exhaustion and AASC impossibility construct the manuscript's 4094
profile population.  No injectivity or cardinal bound occurs in the route
premise.
-/
noncomputable def threePetalBoundedLoadExhaustionOfGeneratedAuthorizerRoute
    {alpha : Type}
    [DecidableEq alpha]
    {r : Nat}
    {F : Concrete.UniformSetFamily alpha (r + 1)}
    {noSunflower : Not (Concrete.HasSunflower 3 F)}
    {corpus : KernelFirstCorpusMachinery
      (Concrete.concreteSunflowerCarrier alpha (r + 1) 3)}
    (classifiers : ResidualParentClassifiers F)
    (route : ThreePetalGeneratedTensorAuthorizerRoute
      F noSunflower corpus classifiers) :
    BoundedPrivateWitnessLoadExhaustion
      (tensorProfileBound :=
        PopulationInheritance.traditionalSeedTensorProfileBound 3
          PopulationInheritance.threePetalTraditionalCutoff)
      noSunflower corpus where
  tensorProfileBound_positive := by
    simp [PopulationInheritance.traditionalSeedTensorProfileBound,
      PopulationInheritance.threePetalTraditionalCutoff]
  constraintProfile := classifiers.constraintProfile
  forcedRole := classifiers.forcedRole
  internalTensorProfileSlot := generatedResidualProfileSlot F noSunflower
  primeChangingTensorSplit :=
    GeneratedResidualParentTensorCollision F noSunflower classifiers
  loadExhaustive := by
    intro left right sameCell sameProfile sameRole load
    by_cases sameGeneratedSlot :
        generatedResidualProfileSlot F noSunflower left =
          generatedResidualProfileSlot F noSunflower right
    · rcases privateWitnessLoad_exhausts_into_boundedSlot_or_residualParent
          F noSunflower left right load with bounded | tensor
      · exact False.elim <| bounded.2 <|
          residualFiberSlot_eq_of_generatedResidualProfileSlot_eq
            F noSunflower left right sameGeneratedSlot
      · exact Or.inr <| Or.inl
          ⟨sameCell, sameProfile, sameRole, sameGeneratedSlot, tensor⟩
    · exact Or.inl sameGeneratedSlot
  primeChangingTensorSplitExcluded := by
    intro left right collision
    rcases route.collisionCreatesIndependentAuthorizer
        left right collision with ⟨factor, authorizer⟩
    exact corpus.fixedDomainClosure.excludesIndependentAuthorizer
      factor authorizer

/--
Rank-uniform generated-data route source.  Its only semantic clause is the
authorizer disposition of a collision left after the concrete six-position
rank-one/residual code has been fixed.
-/
structure DenseThreePetalGeneratedAuthorizerRouteSource
    (alpha : Type)
    [DecidableEq alpha] where
  route :
    forall r : Nat,
      forall F : Concrete.UniformSetFamily alpha (r + 1),
      forall noSunflower : Not (Concrete.HasSunflower 3 F),
      InternalTensorProfiles.internalTensorConstraintBase 3
          (PopulationInheritance.traditionalSeedTensorProfileBound 3
            PopulationInheritance.threePetalTraditionalCutoff) ^ (r + 1) <
        F.edges.card ->
      {classifiers : ResidualParentClassifiers F //
        ThreePetalGeneratedTensorAuthorizerRoute
          F noSunflower
          (BlockerSupportLayers.rankUniformConcreteCorpusMachinery
            alpha 3 (by decide) r)
          classifiers}

noncomputable def
    DenseThreePetalGeneratedAuthorizerRouteSource.toDensePopulationSource
    {alpha : Type}
    [DecidableEq alpha]
    (source : DenseThreePetalGeneratedAuthorizerRouteSource alpha) :
    DenseBoundedPrivateWitnessLoadSource alpha 3
      (PopulationInheritance.traditionalSeedTensorProfileBound 3
        PopulationInheritance.threePetalTraditionalCutoff) (by decide) where
  exhaust := by
    intro r F noSunflower sizeExcess
    let classified := source.route r F noSunflower sizeExcess
    exact threePetalBoundedLoadExhaustionOfGeneratedAuthorizerRoute
      classified.val classified.property

/-- The generated exhaustion/impossibility route feeds the existing endpoint pipeline. -/
theorem sunflower_of_denseThreePetalGeneratedAuthorizerRoute
    {alpha : Type}
    [DecidableEq alpha]
    {n : Nat}
    (source : DenseThreePetalGeneratedAuthorizerRouteSource alpha)
    (F : Concrete.UniformSetFamily alpha n)
    (sizeExcess : 8384512 ^ n < F.edges.card) :
    Concrete.HasSunflower 3 F := by
  apply sunflower_of_dense_boundedPrivateWitnessLoad
    source.toDensePopulationSource F
  simpa [PopulationInheritance.threePetalTraditionalSeedConstraintBase_eq]
    using sizeExcess

/-- The generated route source proves the publication's exact endpoint bound. -/
theorem DenseThreePetalGeneratedAuthorizerRouteSource.provesEndpointBound
    {alpha : Type}
    [DecidableEq alpha]
    (source : DenseThreePetalGeneratedAuthorizerRouteSource alpha) :
    HighRankPopulationInheritance.ThreePetalSeedBaseEndpointBound alpha := by
  intro n F noSunflower
  apply Nat.le_of_not_gt
  intro sizeExcess
  apply noSunflower
  apply sunflower_of_denseThreePetalGeneratedAuthorizerRoute source F
  simpa [PopulationInheritance.threePetalTraditionalSeedConstraintBase_eq]
    using sizeExcess

/-- The endpoint bound supplies the reverse direction of the route correspondence. -/
def denseThreePetalGeneratedAuthorizerRouteSourceOfEndpointBound
    {alpha : Type}
    [DecidableEq alpha]
    (bound : HighRankPopulationInheritance.ThreePetalSeedBaseEndpointBound alpha) :
    DenseThreePetalGeneratedAuthorizerRouteSource alpha where
  route := by
    intro r F noSunflower sizeExcess
    exact False.elim <| Nat.not_lt_of_ge
      (bound (r + 1) F noSunflower) sizeExcess

/--
Exact endpoint correspondence for the rank-uniform authorizer-route
presentation, downstream of the generated finite code.
-/
theorem nonempty_denseThreePetalGeneratedAuthorizerRouteSource_iff_endpointBound
    {alpha : Type}
    [DecidableEq alpha] :
    Nonempty (DenseThreePetalGeneratedAuthorizerRouteSource alpha) <->
      HighRankPopulationInheritance.ThreePetalSeedBaseEndpointBound alpha := by
  constructor
  · intro source
    exact source.some.provesEndpointBound
  · intro bound
    exact ⟨denseThreePetalGeneratedAuthorizerRouteSourceOfEndpointBound bound⟩

end ResidualParentExhaustion
end V2
end SunflowerAASC
